scoring:
  family:
    rating: 0.20
    distance: 0.15
    price-match: 0.10
    available: 0.15
    kid-friendly: 0.30
    time-match: 0.10
  friends:
    rating: 0.30
    distance: 0.15
    price-match: 0.15
    available: 0.20
    vibe-match: 0.20
